"use client";

import { SiteHeader } from "@/components/site-header";
import { FitnessPlan } from "@/components/fitness-plan";
import { ChevronLeft, Sparkles, Download } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function MyPlanPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <SiteHeader />
      
      <main className="max-w-6xl mx-auto px-6 py-10 lg:py-16 space-y-12">
        {/* Breadcrumbs & Actions */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-4">
            <Link href="/chatbot" className="inline-flex items-center gap-2 text-white/40 hover:text-neon-lime transition-colors text-xs font-bold uppercase tracking-widest">
              <ChevronLeft className="w-4 h-4" />
              Back to Coach
            </Link>
            <div className="space-y-2">
              <h1 className="text-4xl lg:text-6xl font-black tracking-tighter uppercase italic leading-none">
                My Fitness <span className="text-neon-lime">Strategy</span>
              </h1>
              <div className="flex items-center gap-2 text-white/40 font-bold uppercase tracking-widest text-xs">
                <Sparkles className="w-4 h-4 text-neon-lime" />
                Generated by AI Coach • Updated Today
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <Button variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 h-12 px-6 rounded-2xl">
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
            <Button className="bg-neon-lime text-black hover:bg-neon-lime/90 h-12 px-6 rounded-2xl font-black">
              Share Plan
            </Button>
          </div>
        </div>

        {/* The Plan */}
        <div className="relative">
            {/* Background Decorations */}
            <div className="absolute top-1/4 -left-20 w-96 h-96 bg-neon-lime/10 rounded-full blur-[120px] pointer-events-none" />
            <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />
            
            <div className="relative z-10">
                <FitnessPlan />
            </div>
        </div>
      </main>

      <footer className="border-t border-white/5 py-10">
        <div className="max-w-6xl mx-auto px-6 text-center text-white/20 text-[10px] font-black uppercase tracking-[0.2em]">
          Trendy Threads • Professional Athlete Support System
        </div>
      </footer>
    </div>
  );
}
